jobs:
  build:
    docker:
    - image: docker:19.03.8
    steps:
    - checkout
    - setup_remote_docker:
        version: 18.09.3
    - run:
        command: DOCKER_BUILDKIT=1 docker build --progress=plain -t tritonmedia/beholder
          -f Dockerfile .
        name: Build "tritonmedia/beholder" Docker Image
    - run:
        command: echo "$DOCKER_PASSWORD" | docker login --username "${DOCKER_USERNAME}"
          --password-stdin && docker push tritonmedia/beholder
        name: Publish "tritonmedia/beholder" Docker Image
version: 2
workflows:
  build-push:
    jobs:
    - build:
        context: Docker
        filters:
          branches:
            only:
            - master
  version: 2
